### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by karan** [2600hz/monster-ui-voip#12]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by JRMaitre** [comment]
Will do!

**Comment by fenollp** [comment]
Fixed by https://github.com/2600hz/monster-ui-voip/commit/89fe70916d51e981f59615bb9421d3046a28b9ae
